// <auto-generated />
using System.Collections.Generic;
using Fleet.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fleet.Server.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260302065328_AddProjectOwnerId")]
    partial class AddProjectOwnerId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fleet.Server.Data.Entities.AgentExecution", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkItemTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("AgentExecutions");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChatSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.ChatSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.DashboardAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DashboardAgents");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.LinkedAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectedAs")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("LinkedAccounts");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastActivity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Slug")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentPlanDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentPlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAI")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.AgentExecution", b =>
                {
                    b.HasOne("Fleet.Server.Data.Entities.Project", "Project")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Fleet.Server.Data.Entities.AgentInfo", "Agents", b1 =>
                        {
                            b1.Property<string>("AgentExecutionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("CurrentTask")
                                .IsRequired();

                            b1.Property<double>("Progress");

                            b1.Property<string>("Role")
                                .IsRequired();

                            b1.Property<string>("Status")
                                .IsRequired();

                            b1.HasKey("AgentExecutionId", "__synthesizedOrdinal");

                            b1.ToTable("AgentExecutions");

                            b1
                                .ToJson("Agents")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentExecutionId");
                        });

                    b.Navigation("Agents");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("Fleet.Server.Data.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.ChatSession", b =>
                {
                    b.HasOne("Fleet.Server.Data.Entities.Project", "Project")
                        .WithMany("ChatSessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.DashboardAgent", b =>
                {
                    b.HasOne("Fleet.Server.Data.Entities.Project", "Project")
                        .WithMany("DashboardAgents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.LinkedAccount", b =>
                {
                    b.HasOne("Fleet.Server.Data.Entities.UserProfile", "UserProfile")
                        .WithMany("LinkedAccounts")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.LogEntry", b =>
                {
                    b.HasOne("Fleet.Server.Data.Entities.Project", "Project")
                        .WithMany("LogEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.Project", b =>
                {
                    b.OwnsOne("Fleet.Server.Data.Entities.AgentSummary", "AgentSummary", b1 =>
                        {
                            b1.Property<string>("ProjectId");

                            b1.Property<int>("Running");

                            b1.Property<int>("Total");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1
                                .ToJson("AgentSummary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("Fleet.Server.Data.Entities.WorkItemSummary", "WorkItemSummary", b1 =>
                        {
                            b1.Property<string>("ProjectId");

                            b1.Property<int>("Active");

                            b1.Property<int>("Resolved");

                            b1.Property<int>("Total");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1
                                .ToJson("WorkItemSummary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("AgentSummary")
                        .IsRequired();

                    b.Navigation("WorkItemSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.Subscription", b =>
                {
                    b.OwnsMany("Fleet.Server.Data.Entities.PlanData", "Plans", b1 =>
                        {
                            b1.Property<int>("SubscriptionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("ButtonAppearance")
                                .IsRequired();

                            b1.Property<string>("ButtonLabel")
                                .IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Features")
                                .IsRequired();

                            b1.Property<string>("Icon")
                                .IsRequired();

                            b1.Property<bool>("IsCurrent");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Period")
                                .IsRequired();

                            b1.Property<string>("Price")
                                .IsRequired();

                            b1.HasKey("SubscriptionId", "__synthesizedOrdinal");

                            b1.ToTable("Subscriptions");

                            b1
                                .ToJson("Plans")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsMany("Fleet.Server.Data.Entities.UsageMeterData", "UsageMeters", b1 =>
                        {
                            b1.Property<int>("SubscriptionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Color")
                                .IsRequired();

                            b1.Property<string>("Label")
                                .IsRequired();

                            b1.Property<string>("Remaining")
                                .IsRequired();

                            b1.Property<string>("Usage")
                                .IsRequired();

                            b1.Property<double>("Value");

                            b1.HasKey("SubscriptionId", "__synthesizedOrdinal");

                            b1.ToTable("Subscriptions");

                            b1
                                .ToJson("UsageMeters")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("Plans");

                    b.Navigation("UsageMeters");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.UserProfile", b =>
                {
                    b.OwnsOne("Fleet.Server.Data.Entities.UserPreferences", "Preferences", b1 =>
                        {
                            b1.Property<int>("UserProfileId");

                            b1.Property<bool>("AgentCompletedNotification");

                            b1.Property<bool>("AgentErrorsNotification");

                            b1.Property<bool>("CompactMode");

                            b1.Property<bool>("DarkMode");

                            b1.Property<bool>("PrOpenedNotification");

                            b1.Property<bool>("SidebarCollapsed");

                            b1.Property<bool>("WorkItemUpdatesNotification");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1
                                .ToJson("Preferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.WorkItem", b =>
                {
                    b.HasOne("Fleet.Server.Data.Entities.WorkItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fleet.Server.Data.Entities.Project", "Project")
                        .WithMany("WorkItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.Project", b =>
                {
                    b.Navigation("AgentExecutions");

                    b.Navigation("ChatSessions");

                    b.Navigation("DashboardAgents");

                    b.Navigation("LogEntries");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.UserProfile", b =>
                {
                    b.Navigation("LinkedAccounts");
                });

            modelBuilder.Entity("Fleet.Server.Data.Entities.WorkItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
