import { tokens } from '@fluentui/react-components'

const cssVar = (name: string) => `var(${name})`

export const APP_MOBILE_MAX_WIDTH = 900
export const APP_NARROW_LAYOUT_MAX_WIDTH = 1000
export const APP_MOBILE_MEDIA_QUERY = `(max-width: ${APP_MOBILE_MAX_WIDTH}px)`
export const APP_NARROW_LAYOUT_MEDIA_QUERY = `(max-width: ${APP_NARROW_LAYOUT_MAX_WIDTH}px)`

export const appTokens = {
    color: {
        pageBackground: tokens.colorNeutralBackground3,
        surface: tokens.colorNeutralBackground1,
        surfaceAlt: tokens.colorNeutralBackground2,
        surfaceAltHover: tokens.colorNeutralBackground2Hover,
        surfaceRaised: tokens.colorNeutralBackground5,
        surfaceHover: tokens.colorNeutralBackground1Hover,
        surfacePressed: tokens.colorNeutralBackground1Pressed,
        surfaceSelected: tokens.colorNeutralBackground1Selected,
        surfaceBrand: tokens.colorBrandBackground2,
        surfaceBrandHover: tokens.colorBrandBackground2Hover,
        surfaceBrandSolid: tokens.colorBrandBackground,
        onBrandSurfaceSoft: cssVar('--app-on-brand-surface-soft'),
        onBrandSurfaceMuted: cssVar('--app-on-brand-surface-muted'),
        onBrandSurfaceStrong: cssVar('--app-on-brand-surface-strong'),
        onBrandBorderSoft: cssVar('--app-on-brand-border-soft'),
        onBrandBorderStrong: cssVar('--app-on-brand-border-strong'),
        onBrandTextMuted: cssVar('--app-on-brand-text-muted'),
        textPrimary: tokens.colorNeutralForeground1,
        textSecondary: tokens.colorNeutralForeground2,
        textTertiary: tokens.colorNeutralForeground3,
        textMuted: tokens.colorNeutralForeground4,
        textOnBrand: tokens.colorNeutralForegroundOnBrand,
        brand: tokens.colorBrandForeground1,
        brandStroke: tokens.colorBrandStroke1,
        focusOutline: tokens.colorStrokeFocus2,
        success: tokens.colorPaletteGreenForeground1,
        warning: tokens.colorPaletteMarigoldForeground1,
        danger: tokens.colorPaletteRedForeground1,
        accentOrange: tokens.colorPaletteDarkOrangeForeground1,
        googleBlue: cssVar('--app-google-blue'),
        googleGreen: cssVar('--app-google-green'),
        googleYellow: cssVar('--app-google-yellow'),
        googleRed: cssVar('--app-google-red'),
        workItemLevelDefault: cssVar('--app-work-item-level-default'),
        border: tokens.colorNeutralStroke2,
        borderSubtle: tokens.colorNeutralStroke3,
        overlayBackdrop: cssVar('--app-overlay-backdrop'),
        authGlowA: cssVar('--app-auth-glow-a'),
        authGlowB: cssVar('--app-auth-glow-b'),
    },
    space: {
        xxxs: cssVar('--app-space-3xs'),
        xxs: cssVar('--app-space-2xs'),
        xs: cssVar('--app-space-xs'),
        sm: cssVar('--app-space-sm'),
        md: cssVar('--app-space-md'),
        lg: cssVar('--app-space-lg'),
        xl: cssVar('--app-space-xl'),
        xxl: cssVar('--app-space-2xl'),
        pageX: cssVar('--app-page-padding-x'),
        pageXMobile: cssVar('--app-page-padding-x-mobile'),
        pageYMobile: cssVar('--app-page-padding-y-mobile'),
    },
    fontSize: {
        xxs: cssVar('--app-font-size-2xs'),
        xs: cssVar('--app-font-size-xs'),
        sm: cssVar('--app-font-size-sm'),
        md: cssVar('--app-font-size-md'),
        lg: cssVar('--app-font-size-lg'),
        xl: cssVar('--app-font-size-xl'),
        metric: cssVar('--app-font-size-metric'),
        iconXs: cssVar('--app-font-size-icon-xs'),
        iconSm: cssVar('--app-font-size-icon-sm'),
        iconMd: cssVar('--app-font-size-icon-md'),
        iconLg: cssVar('--app-font-size-icon-lg'),
        iconXl: cssVar('--app-font-size-icon-xl'),
    },
    lineHeight: {
        tight: cssVar('--app-line-height-tight'),
        snug: cssVar('--app-line-height-snug'),
        base: cssVar('--app-line-height-base'),
        relaxed: cssVar('--app-line-height-relaxed'),
    },
    fontWeight: {
        medium: tokens.fontWeightMedium,
        semibold: tokens.fontWeightSemibold,
        bold: tokens.fontWeightBold,
    },
    fontFamily: {
        monospace: tokens.fontFamilyMonospace,
    },
    size: {
        topBar: cssVar('--app-shell-top-bar-height'),
        topBarCompact: cssVar('--app-shell-top-bar-height-compact'),
        topBarMobile: cssVar('--app-shell-top-bar-height-mobile'),
        sidebarHeader: cssVar('--app-shell-sidebar-header-height'),
        sidebarExpanded: cssVar('--app-shell-sidebar-width'),
        sidebarExpandedCompact: cssVar('--app-shell-sidebar-width-compact'),
        sidebarCollapsed: cssVar('--app-shell-sidebar-collapsed-width'),
        sidebarCollapsedCompact: cssVar('--app-shell-sidebar-collapsed-width-compact'),
        mobileSidebarWidth: cssVar('--app-shell-mobile-sidebar-width'),
        chatDefault: cssVar('--app-shell-chat-width-default'),
        chatMin: cssVar('--app-shell-chat-width-min'),
        chatMax: cssVar('--app-shell-chat-width-max'),
        logPanelMaxHeight: cssVar('--app-monitor-log-max-height'),
    },
    width: {
        pageNarrow: cssVar('--app-page-max-width-narrow'),
        pageMedium: cssVar('--app-page-max-width-medium'),
        pageLarge: cssVar('--app-page-max-width-large'),
        projectCardMin: cssVar('--app-project-card-min-width'),
        quickActionMin: cssVar('--app-quick-action-min-width'),
        metricCardMin: cssVar('--app-metric-card-min-width'),
        planCardMin: cssVar('--app-plan-card-min-width'),
    },
    palette: {
        workItemLevels: [
            cssVar('--app-work-item-level-1'),
            cssVar('--app-work-item-level-2'),
            cssVar('--app-work-item-level-3'),
            cssVar('--app-work-item-level-4'),
            cssVar('--app-work-item-level-5'),
            cssVar('--app-work-item-level-6'),
            cssVar('--app-work-item-level-7'),
            cssVar('--app-work-item-level-8'),
            cssVar('--app-work-item-level-9'),
            cssVar('--app-work-item-level-10'),
            cssVar('--app-work-item-level-11'),
            cssVar('--app-work-item-level-12'),
        ],
    },
    radius: {
        sm: tokens.borderRadiusSmall,
        md: tokens.borderRadiusMedium,
        lg: tokens.borderRadiusLarge,
        xl: tokens.borderRadiusXLarge,
        full: cssVar('--app-radius-full'),
    },
    shadow: {
        card: tokens.shadow4,
        cardHover: tokens.shadow8,
        overlay: tokens.shadow64,
    },
    motion: {
        fast: cssVar('--app-motion-fast'),
        normal: cssVar('--app-motion-normal'),
    },
    border: {
        subtle: `1px solid ${tokens.colorNeutralStroke2}`,
        subtleAlt: `1px solid ${tokens.colorNeutralStroke3}`,
        brand: `1px solid ${tokens.colorBrandStroke1}`,
        activeInset: `inset 0 0 0 1px ${tokens.colorBrandStroke1}`,
    },
    zIndex: {
        sidebarBackdrop: 30,
        sidebarDrawer: 31,
        chatOverlay: 40,
        workItemOverlay: 900,
        workItemPanel: 1000,
    },
}
