import { tokens } from '@fluentui/react-components'

const cssVar = (name: string) => `var(${name})`

export const WEBSITE_MOBILE_MAX_WIDTH = 900
export const WEBSITE_TABLET_MAX_WIDTH = 768

export const appTokens = {
    color: {
        pageBackground: cssVar('--app-page-background'),
        surface: cssVar('--app-surface'),
        surfaceAlt: cssVar('--app-surface-alt'),
        surfaceAltHover: cssVar('--app-surface-alt-hover'),
        surfaceRaised: cssVar('--app-surface-raised'),
        surfaceHover: cssVar('--app-surface-hover'),
        surfacePressed: cssVar('--app-surface-pressed'),
        surfaceSelected: cssVar('--app-surface-selected'),
        surfaceBrand: cssVar('--app-surface-brand'),
        surfaceBrandHover: cssVar('--app-surface-brand-hover'),
        surfaceBrandSolid: cssVar('--app-surface-brand-solid'),
        onBrandSurfaceSoft: cssVar('--app-on-brand-surface-soft'),
        onBrandSurfaceMuted: cssVar('--app-on-brand-surface-muted'),
        onBrandSurfaceStrong: cssVar('--app-on-brand-surface-strong'),
        onBrandBorderSoft: cssVar('--app-on-brand-border-soft'),
        onBrandBorderStrong: cssVar('--app-on-brand-border-strong'),
        onBrandTextMuted: cssVar('--app-on-brand-text-muted'),
        textPrimary: cssVar('--app-text-primary'),
        textSecondary: cssVar('--app-text-secondary'),
        textTertiary: cssVar('--app-text-tertiary'),
        textMuted: cssVar('--app-text-muted'),
        textOnBrand: cssVar('--app-text-on-brand'),
        brand: cssVar('--app-brand'),
        brandHover: cssVar('--app-brand-hover'),
        brandActive: cssVar('--app-brand-active'),
        brandMuted: cssVar('--app-brand-muted'),
        brandStroke: cssVar('--app-border-brand'),
        focusOutline: cssVar('--app-focus-outline'),
        success: cssVar('--app-success'),
        warning: cssVar('--app-warning'),
        danger: cssVar('--app-danger'),
        info: cssVar('--app-info'),
        infoSurface: cssVar('--app-info-surface'),
        infoBorder: cssVar('--app-info-border'),
        accentOrange: cssVar('--app-accent-orange'),
        border: cssVar('--app-border-default'),
        borderSubtle: cssVar('--app-border-subtle'),
        borderStrong: cssVar('--app-border-strong'),
    },
    space: {
        xxxs: cssVar('--app-space-3xs'),
        xxs: cssVar('--app-space-2xs'),
        xs: cssVar('--app-space-xs'),
        sm: cssVar('--app-space-sm'),
        md: cssVar('--app-space-md'),
        lg: cssVar('--app-space-lg'),
        xl: cssVar('--app-space-xl'),
        xxl: cssVar('--app-space-2xl'),
        xxxl: cssVar('--app-space-3xl'),
        pageX: cssVar('--app-page-padding-x'),
        pageXMobile: cssVar('--app-page-padding-x-mobile'),
        pageYMobile: cssVar('--app-page-padding-y-mobile'),
    },
    fontSize: {
        xxs: cssVar('--app-font-size-2xs'),
        xs: cssVar('--app-font-size-xs'),
        sm: cssVar('--app-font-size-sm'),
        md: cssVar('--app-font-size-md'),
        lg: cssVar('--app-font-size-lg'),
        xl: cssVar('--app-font-size-xl'),
        iconSm: cssVar('--app-font-size-icon-sm'),
        iconMd: cssVar('--app-font-size-icon-md'),
        iconLg: cssVar('--app-font-size-icon-lg'),
        iconXl: cssVar('--app-font-size-icon-xl'),
        hero: tokens.fontSizeHero800,
    },
    lineHeight: {
        tight: cssVar('--app-line-height-tight'),
        snug: cssVar('--app-line-height-snug'),
        base: cssVar('--app-line-height-base'),
        relaxed: cssVar('--app-line-height-relaxed'),
        hero: tokens.lineHeightHero800,
    },
    fontWeight: {
        regular: tokens.fontWeightRegular,
        medium: tokens.fontWeightMedium,
        semibold: tokens.fontWeightSemibold,
        bold: tokens.fontWeightBold,
    },
    radius: {
        sm: tokens.borderRadiusSmall,
        md: tokens.borderRadiusMedium,
        lg: tokens.borderRadiusLarge,
        xl: tokens.borderRadiusXLarge,
        full: cssVar('--app-radius-full'),
    },
    shadow: {
        card: tokens.shadow4,
        cardHover: tokens.shadow8,
    },
    border: {
        subtle: `1px solid ${cssVar('--app-border-default')}`,
        subtleAlt: `1px solid ${cssVar('--app-border-subtle')}`,
        strong: `1px solid ${cssVar('--app-border-strong')}`,
        brand: `1px solid ${cssVar('--app-border-brand')}`,
    },
    width: {
        pageNarrow: cssVar('--app-page-max-width-narrow'),
        pageMedium: cssVar('--app-page-max-width-medium'),
        pageLarge: cssVar('--app-page-max-width-large'),
        planCardMin: cssVar('--app-plan-card-min-width'),
    },
}
