export { ApiError, getApiErrorMessage, setTokenGetter, fetchWithAuth, get, post, put, del, postForm } from './proxy'
export {
  getProjects,
  getProjectDashboard,
  getProjectDashboardBySlug,
  createProject,
  updateProject,
  deleteProject,
  checkSlug,
  exportProjectsFile,
  importProjectsFile,
} from './projectsProxy'
export type { CreateProjectRequest, UpdateProjectRequest, ProjectsImportResult } from './projectsProxy'
export {
  getWorkItems,
  getWorkItemAttachments,
  createWorkItem,
  updateWorkItem,
  uploadWorkItemAttachment,
  deleteWorkItemAttachment,
  bulkUpdateWorkItems,
  bulkDeleteWorkItems,
  deleteWorkItem,
  exportWorkItemsFile,
  importWorkItemsFile,
} from './workItemsProxy'
export type { CreateWorkItemRequest, UpdateWorkItemRequest, WorkItemsImportResult } from './workItemsProxy'
export { getWorkItemLevels, createWorkItemLevel, updateWorkItemLevel, deleteWorkItemLevel } from './levelsProxy'
export type { CreateWorkItemLevelRequest, UpdateWorkItemLevelRequest } from './levelsProxy'
export {
  getExecutions,
  getLogs,
  clearLogs,
  clearExecutionLogs,
  startExecution,
  getExecutionStatus,
  cancelExecution,
  pauseExecution,
  resumeExecution,
  steerExecution,
  retryExecution,
  deleteExecution,
  getExecutionDocumentation,
} from './agentsProxy'
export type { ExecutionStatus, ExecutionDocumentation } from './agentsProxy'
export { getChatData, getMessages, createChatSession, sendChatMessage, getAttachments, uploadAttachment, deleteAttachment, deleteChatSession, renameChatSession, cancelChatGeneration, cancelChatSessionRequests, updateChatSessionDynamicIteration } from './chatProxy'
export type { UpdateSessionDynamicIterationRequest } from './chatProxy'
export { search } from './searchProxy'
export { getSubscription } from './subscriptionProxy'
export {
  getLoginIdentities,
  createLoginProviderLinkState,
  completeLoginProviderLink,
  deleteLoginIdentity,
} from './authProxy'
export {
  getUserSettings,
  updateProfile,
  updatePreferences,
  getUserMemories,
  createUserMemory,
  updateUserMemory,
  deleteUserMemory,
  getProjectMemories,
  createProjectMemory,
  updateProjectMemory,
  deleteProjectMemory,
  getSkillTemplates,
  getUserSkills,
  createUserSkill,
  updateUserSkill,
  deleteUserSkill,
  getProjectSkills,
  createProjectSkill,
  updateProjectSkill,
  deleteProjectSkill,
  getGitHubOAuthState,
  getGitHubOAuthClientId,
  linkGitHub,
  unlinkGitHub,
  setPrimaryGitHubAccount,
  getGitHubRepos,
  createGitHubRepo,
  getMcpServers,
  getMcpServerTemplates,
  getSystemMcpServers,
  createMcpServer,
  updateMcpServer,
  deleteMcpServer,
  validateMcpServer,
} from './userProxy'
export type {
  CreateGitHubRepoRequest,
  UpsertMcpServerRequest,
  UpsertMcpServerVariableRequest,
  UpsertMemoryEntryRequest,
  UpsertPromptSkillRequest,
} from './userProxy'
export { getNotifications, markNotificationAsRead, markAllNotificationsAsRead } from './notificationProxy'
export {
  useDataQuery,
  useProjects,
  useProjectDashboard,
  useProjectDashboardBySlug,
  useCheckSlug,
  useCreateProject,
  useUpdateProject,
  useDeleteProject,
  useExportProjects,
  useImportProjects,
  useWorkItems,
  useExportWorkItems,
  useImportWorkItems,
  useWorkItemLevels,
  useExecutions,
  useLogs,
  useClearLogs,
  useClearExecutionLogs,
  useStartExecution,
  useCancelExecution,
  usePauseExecution,
  useResumeExecution,
  useRetryExecution,
  useDeleteExecution,
  useExecutionDocumentation,
  useChatData,
  useChatMessages,
  useSearch,
  useSubscription,
  useUserSettings,
  useUpdateProfile,
  useUpdatePreferences,
  useLoginIdentities,
  useDeleteLoginIdentity,
  useUserMemories,
  useCreateUserMemory,
  useUpdateUserMemory,
  useDeleteUserMemory,
  useProjectMemories,
  useCreateProjectMemory,
  useUpdateProjectMemory,
  useDeleteProjectMemory,
  useSkillTemplates,
  useUserSkills,
  useCreateUserSkill,
  useUpdateUserSkill,
  useDeleteUserSkill,
  useProjectSkills,
  useCreateProjectSkill,
  useUpdateProjectSkill,
  useDeleteProjectSkill,
  useLinkGitHub,
  useUnlinkGitHub,
  useSetPrimaryGitHubAccount,
  useGitHubRepos,
  useCreateGitHubRepo,
  useMcpServers,
  useMcpServerTemplates,
  useSystemMcpServers,
  useCreateMcpServer,
  useUpdateMcpServer,
  useDeleteMcpServer,
  useValidateMcpServer,
  useCreateWorkItem,
  useWorkItemAttachments,
  useUploadWorkItemAttachment,
  useDeleteWorkItemAttachment,
  useUpdateWorkItem,
  useBulkUpdateWorkItems,
  useBulkDeleteWorkItems,
  useDeleteWorkItem,
  useCreateWorkItemLevel,
  useUpdateWorkItemLevel,
  useDeleteWorkItemLevel,
  useCreateChatSession,
  useCancelChatGeneration,
  useSendMessage,
  useAttachments,
  useUploadAttachment,
  useDeleteAttachment,
  useDeleteSession,
  useRenameSession,
  useUpdateSessionDynamicIteration,
  useNotifications,
  useMarkNotificationAsRead,
  useMarkAllNotificationsAsRead,
} from './dataClient'
export type { DataResult } from './dataClient'
export { resolveIcon } from './iconMap'
export { resolveLevelIcon, LEVEL_ICON_NAMES } from './levelIconMap'
